### ISSUE TITLE
Two small issues with Wide printer

### ISSUE THREAD

**Issue by jirka-grunt** [javl/InstaxBLE#12]
Hi,

first of all, thank you for creating this project - it's nice to be able to print with an open source program. I only had two minor problems with InstaxBLE.py:

1. There is invalid size for "wide" printer, 1260x800 instead of 1260x840 (line 110), so printer is not detected.
2. Printing status info is too fast, it will happen before printer's response is parsed, so I had to add small delay (sleep 1) between get_printer_info() and display_current_status() to see photos left etc. (lines 209-210). Probably same casuse as #11.

I hope this report helps, Jirka

**Comment by javl** [comment]
Hi @jirka-grunt 
1. I feel like this image size thing keeps popping up. Can you confirm it does work when you change the code to search for 1260x840? If so I'll update it
2. Ah yeah, that might be why I wasn't always getting the number of images left. The way the script is set up it should wait for the message from the printer to come in before trying to parse it, but as you mentioned the timing is still far from perfect.

Thanks for the notes.

**Comment by jirka-grunt** [comment]
@javl Yes, I successfully printed package of photos from 1260x840 images. All other places were already changed, only here old dimension 800 remained.

**Comment by javl** [comment]
Ah, ok! I’ll try to remember updating it when I get the time, thanks. On 24 Oct 2023, at 10:53, Jirka Grunt ***@***.***> wrote:﻿
@javl Yes, I successfully printed package of photos from 1260x840 images. All other places were already changed, only here old dimension 800 remained.

**Comment by javl** [comment]
Finally updated the Wide size properly, and I've added the delay you suggested as well, thanks again.
