### ISSUE TITLE
RuntimeError InstaxBLE.py 497

### ISSUE THREAD

**Issue by sidharthb0** [javl/InstaxBLE#13]
Thanks for creating this library, I've been looking forward to trying it out!

Just got my printer a few days ago and I've been trying to connect using InstaxBLE running on raspberry pi. The first time I ran the script (which btw in your instructions is instax-ble.py, but in the codebase is InstaxBLE.py -- side note), it connected to the printer and logged a bunch of information about the printer. 

Then I deactivated the venv to go write another custom script and was using InstaxBLE.py as a reference. At some point I ran InstaxBLE.py again and received a RuntimeError InstaxBLE.py 497. Subsequently I am receiving the same error every time I run it now. I have even tried to delete the folder and clone it again (in case I made some breaking changes) but with no luck.

Any idea what could be causing this? Your help is appreciated. Thanks and regards!

**Comment by javl** [comment]
Haha yeah the repo has gone through a couple of names. I'll check if I can straighten it out at some point. 

Do you get a specific error you can share?

**Comment by sidharthb0** [comment]
So the printer turns on with the rainbow lights as expected and then the LED stays white. That’s when I execute the InstaxBLE.py file and after a few seconds, I just get **Runtime Error InstaxBLE.py 497**. The status led on the printer doesn’t change. 

I tried restarting the printer and also cloning the repo fresh but without luck.

**Comment by sidharthb0** [comment]
Resolved this issue by removing the device from the device list on the pi, rebooting and connecting again!

**Comment by javl** [comment]
Great, and thanks for providing feedback on your solution.

**Comment by sidharthb0** [comment]
While I have you, quick question - I’m working on integrating this with PiBooth and using this library instead of the cups printing option available there. Only thing - I’m super new to python. Any chance we could work on building a InstaxBLE plugin for PiBooth together? It’ll produce that awesome Polaroid feel with an already awesome Photo Booth setup.
