### ISSUE TITLE
not able to print to instax wide

### ISSUE THREAD

**Issue by samstinson** [javl/InstaxBLE#20]
I'm running on RPi, fwiw. I am able to print the test pattern just fine, but my own images are not being sent. It appears to be disconnecting early and never gets the print confirmation, and after a bit the Instax Link starts flashing yellow. I'm able to print this image successfully from the iOS app.

# print test pattern
./InstaxBLE.py --print-enabled -v
Searching for instax printer...
Connecting to INSTAX-20163905(IOS) [FA:AB:BC:59:15:3E]
Connected

Printer details: 
Model:               Instax Wide Link
Photos left:         10/10
Battery level:       50%
Charging:            False
Required image size: 1260x840px
MTU:                 65533

printing image "example-wide.jpg"
Saved img with quality of 100
Img packets left to send: 100
Img packets left to send: 90
Img packets left to send: 80
Img packets left to send: 70
Img packets left to send: 60
Img packets left to send: 50
Img packets left to send: 40
Img packets left to send: 30
Img packets left to send: 20
Img packets left to send: 10
received print confirmation
finally, disconnect
Disconnecting...
Disconnected

# print my own image
/InstaxBLE.py --print-enabled -v -i /opt/img/1727122372_cr.jpg
Searching for instax printer...
Connecting to INSTAX-20163905(IOS) [FA:AB:BC:59:15:3E]
Connected

Printer details: 
Model:               Instax Wide Link
Photos left:         8/10
Battery level:       100%
Charging:            True
Required image size: 1260x840px
MTU:                 65533

printing image "/opt/img/1727122372_cr.jpg"
Saved img with quality of 48
Printing is enabled, sending print command
Img packets left to send: 170
Img packets left to send: 160
Img packets left to send: 150
Img packets left to send: 140
Img packets left to send: 130
Img packets left to send: 120
Img packets left to send: 110
Img packets left to send: 100
Img packets left to send: 90
Img packets left to send: 80
Img packets left to send: 70
Img packets left to send: 60
Img packets left to send: 50
finally, disconnect
Disconnecting...
Disconnected

My image : 
![1727122372_cr](https://github.com/user-attachments/assets/e7afaf8f-c9b2-4308-b6bb-2de6bbf9e213)

**Comment by javl** [comment]
Hey, sorry for not responding sooner. 

The first thing I'd ask you to try is to check if you're actually enabling printing. To prevent wasting images while testing your code, printing is disabled by default, which means your image will be send to the printer, but we won't send the actual 'go print' command:

You can see a code [example here](https://github.com/javl/InstaxBLE?tab=readme-ov-file#1-printing-is-disabled-by-default)

**Comment by javl** [comment]
Closing this as there hasn't been any response.
