### ISSUE TITLE
AttributeError: module 'socket' has no attribute 'AF_BLUETOOTH'

### ISSUE THREAD

**Issue by caichunjian520** [javl/InstaxBLE#3]
When I run `python3 InstaxBLE.py`, it shows error AttributeError: module 'socket' has no attribute 'AF_BLUETOOTH'

I have run these step by step
git clone https://github.com/javl/InstaxBLE.git
cd InstaxBle
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
python3 InstaxBLE.py

**Comment by javl** [comment]
Ah, turns out those sockets dont work on Windows. I'll see if there is an alternative.

**Comment by caichunjian520** [comment]
I use macbook, MacOS Monterey

**Comment by javl** [comment]
I think the socket should work on Mac, but I'll try and change the code to use a different method. I'll post here if/when that works.

**Comment by javl** [comment]
Hey @caichunjian520 
Could you give this branch a try? I removed the need for sockets, I think this should work.
Every now and then I do get some error (like `le-connection-abort-by-local`) but restart the code to try again.

**Comment by caichunjian520** [comment]
@javl Thanks, I will try it tomorrow.

**Comment by caichunjian520** [comment]
@javl I just tried with gatt branch，it works.
Looking for instax printer...
INSTAX-10458647(IOS)
Printing is disabled

I know if I want to print photo，I should change the code to instax = InstaxBle(enablePrinting=True)
But there are 2/10 Film Sheets left for me to play with other features.

**Comment by javl** [comment]
Without actual printing you still don't know if it works, but at least the socket problem has been fixed ;)

**Comment by javl** [comment]
Reopening as I think the actual printing doesn't work yet

**Comment by zoz06** [comment]
Hi and thanks for your work. I'm having too the same bug with Macos BigSur and the main branch. Just a question: what should I type to get the gatt (or the new test gatt?) branch:
I typed but I don't find any difference with the gatt. Sorry I'm a noob in this domain.
git clone https://github.com/javl/InstaxBLE.git
cd InstaxBle
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
python3 InstaxBLE.py

**Comment by javl** [comment]
@zoz06 you should be able to type `git checkout gatt` to switch to the other branch. Not sure how well it works at the moment, I've been moving some things around and need to improve it.

**Comment by javl** [comment]
@caichunjian520 If you're still interested: I've updated all the code and it now works on MacOS as well! Just tested on a Macbook Air using macOS Monterey.
