### ISSUE TITLE
Instax Mini Link 2

### ISSUE THREAD

**Issue by mainrs** [javl/InstaxBLE#6]
Are there plans to support the [new](https://instax.com/mini_link_2/en/) device?

**Comment by javl** [comment]
I'd love to but I only have the first Link Mini device. Have you tried the code with the Link 2? I don't know if anything actually changed but I think it should still work (seeing as the Android app I based my code on is used for both models). Feel free to ask Instax to send me a couple of printers to test with ;)

**Comment by mainrs** [comment]
I wanted to ask for some clarification. The program does only send over an image to the printer. The image has to be created by some other program beforehand. So collages and other features are not available.

**Comment by javl** [comment]
This script is meant to control the camera and (some of) its functions. The collage part is done by the app; you could use any piece of software to generate those.
